In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import warnings
warnings.filterwarnings("ignore")

In [4]:
df = pd.read_csv('/content/drive/MyDrive/Aprendizado de Máquina Supervision/train-tratado.csv',
                    encoding='utf-8')

In [5]:
df.head()

   PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            2         1       1  female  38.0      1      0  71.2833        C
1            4         1       1  female  35.0      1      0  53.1000        S
2            7         0       1    male  54.0      0      0  51.8625        S
3           11         1       3  female   4.0      1      1  16.7000        S
4           12         1       1  female  58.0      0      0  26.5500        S

In [6]:
df.shape

(183, 9)

##Coluna Alvo

alvo: porto de embarque

##Legenda

PassengerId = id passageiro

Survived = sobreviventes (número de sobreviventes)

Pclass: classe do ingresso (número de pessoas por cabine)

Sex: sexo (0=feminino, 1=masculino)

Age: idade

SibSp: número de irmãos / cônjugues a bordo

Parch: número de pais / filhos a bordo

Fare: tarifa de passageiro

Embarked: porto de embarque

## **Transformando as variáveis categóricas nominais**

### **LabelEncoder**

In [7]:
df2 = pd.DataFrame.copy(df)

In [8]:
df2['Sex'].replace({'female':0, 'male': 1}, inplace=True)
df2['Embarked'].replace({'C': 0, 'Q': 1, 'S': 2}, inplace=True)

In [9]:
df2.head()

   PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0            2         1       1    0  38.0      1      0  71.2833         0
1            4         1       1    0  35.0      1      0  53.1000         2
2            7         0       1    1  54.0      0      0  51.8625         2
3           11         1       3    0   4.0      1      1  16.7000         2
4           12         1       1    0  58.0      0      0  26.5500         2

In [10]:
df2.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Sex              int64
Age            float64
SibSp            int64
Parch            int64
Fare           float64
Embarked         int64
dtype: object

In [11]:
df2.shape

(183, 9)

### OneHotEncoder

In [12]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [13]:
encoder = OneHotEncoder()
oneHotEncoder = encoder.fit_transform(df[['Sex', 'Pclass', 'SibSp', 'Embarked', 'Parch']])

In [14]:
oneHotEncoder.todense()

matrix([[1., 0., 1., ..., 0., 0., 0.],
        [1., 0., 1., ..., 0., 0., 0.],
        [0., 1., 1., ..., 0., 0., 0.],
        ...,
        [1., 0., 1., ..., 1., 0., 0.],
        [1., 0., 1., ..., 0., 0., 0.],
        [0., 1., 1., ..., 0., 0., 0.]])

In [15]:
oneHotEncoder.shape

(183, 16)

In [16]:
nome_colunas = encoder.get_feature_names(['Sex', 'Pclass', 'SibSp', 'Embarked', 'Parch'])
df3_encoder = pd.DataFrame(oneHotEncoder.todense(), columns= nome_colunas)
df3_encoder

,Sex_female,Sex_male,Pclass_1,Pclass_2,Pclass_3,SibSp_0,SibSp_1,SibSp_2,SibSp_3,Embarked_C,Embarked_Q,Embarked_S,Parch_0,Parch_1,Parch_2,Parch_4
0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
2,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
4,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
179,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
180,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
181,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
182,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0

In [17]:
df3 = pd.concat([df, df3_encoder], axis=1).drop(['Sex', 'Pclass', 'SibSp', 'Embarked', 'Parch'], axis=1)
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183 entries, 0 to 182
Data columns (total 20 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  183 non-null    int64
 1   Survived     183 non-null    int64
 2   Age          183 non-null    float64
 3   Fare         183 non-null    float64
 4   Sex_female   183 non-null    float64
 5   Sex_male     183 non-null    float64
 6   Pclass_1     183 non-null    float64
 7   Pclass_2     183 non-null    float64
 8   Pclass_3     183 non-null    float64
 9   SibSp_0      183 non-null    float64
 10  SibSp_1      183 non-null    float64
 11  SibSp_2      183 non-null    float64
 12  SibSp_3      183 non-null    float64
 13  Embarked_C   183 non-null    float64
 14  Embarked_Q   183 non-null    float64
 15  Embarked_S   183 non-null    float64
 16  Parch_0      183 non-null    float64
 17  Parch_1      183 non-null    float64
 18  Parch_2      183 non-null    float64
 19  Parch_4      183 non-null    float64
dtypes: float64(18), int64(2)
memory usage: 28.7 KB

##Legenda

PassengerId = id passageiro

Survived = sobreviventes (número de sobreviventes)

Pclass: classe do ingresso (número de pessoas por cabine)

Sex: sexo (0=feminino, 1=masculino)

Age: idade

SibSp: número de irmãos / cônjugues a bordo

Parch: número de pais / filhos a bordo

Fare: tarifa de passageiro

Embarked: porto de embarque

## Previsores e Alvo

In [18]:
df2.head()

   PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0            2         1       1    0  38.0      1      0  71.2833         0
1            4         1       1    0  35.0      1      0  53.1000         2
2            7         0       1    1  54.0      0      0  51.8625         2
3           11         1       3    0   4.0      1      1  16.7000         2
4           12         1       1    0  58.0      0      0  26.5500         2

In [19]:
previsores = df2.iloc[:, 0:8].values

In [20]:
previsores

array([[  2.    ,   1.    ,   1.    , ...,   1.    ,   0.    ,  71.2833],
       [  4.    ,   1.    ,   1.    , ...,   1.    ,   0.    ,  53.1   ],
       [  7.    ,   0.    ,   1.    , ...,   0.    ,   0.    ,  51.8625],
       ...,
       [880.    ,   1.    ,   1.    , ...,   0.    ,   1.    ,  83.1583],
       [888.    ,   1.    ,   1.    , ...,   0.    ,   0.    ,  30.    ],
       [890.    ,   1.    ,   1.    , ...,   0.    ,   0.    ,  30.    ]])

In [21]:
previsores.shape

(183, 8)

In [22]:
alvo = df2.iloc[:, 8].values

In [23]:
alvo

array([0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 2,
       2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 0, 0, 2, 0, 0, 0, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 2, 0, 0, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 2,
       2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 2, 1, 2, 2, 2, 2, 2, 2,
       2, 0, 0, 2, 2, 2, 0, 0, 2, 0, 2, 0, 2, 2, 0, 2, 2, 2, 2, 0, 2, 0,
       2, 0, 0, 0, 2, 2, 2, 2, 0, 0, 2, 0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 0,
       0, 0, 0, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0,
       2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2,
       2, 2, 2, 2, 0, 2, 0])

In [24]:
alvo.shape

(183,)

##Escalonamento

Padronização (utiliza a média e o desvio padrão como referência).

In [30]:
df2.describe()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
count,183.000000,183.000000,183.000000,183.000000,183.000000,183.000000,183.000000,183.000000,183.000000
mean,455.366120,0.672131,1.191257,0.519126,35.674426,0.464481,0.475410,78.682469,1.278689
std,247.052476,0.470725,0.515187,0.501005,15.643866,0.644159,0.754617,76.347843,0.957294
min,2.000000,0.000000,1.000000,0.000000,0.920000,0.000000,0.000000,0.000000,0.000000
25%,263.500000,0.000000,1.000000,0.000000,24.000000,0.000000,0.000000,29.700000,0.000000
50%,457.000000,1.000000,1.000000,1.000000,36.000000,0.000000,0.000000,57.000000,2.000000
75%,676.000000,1.000000,1.000000,1.000000,47.500000,1.000000,1.000000,90.000000,2.000000
max,890.000000,1.000000,3.000000,1.000000,80.000000,3.000000,4.000000,512.329200,2.000000

In [31]:
from sklearn.preprocessing import StandardScaler

In [32]:
previsores_esc = StandardScaler().fit_transform(previsores)

In [33]:
previsores_esc

array([[-1.84013507,  0.6984303 , -0.37225618, ...,  0.83362754,
        -0.63172982, -0.0971798 ],
       [-1.83201742,  0.6984303 , -0.37225618, ...,  0.83362754,
        -0.63172982, -0.3359971 ],
       [-1.81984093, -1.43178211, -0.37225618, ..., -0.7230443 ,
        -0.63172982, -0.35225028],
       ...,
       [ 1.72351585,  0.6984303 , -0.37225618, ..., -0.7230443 ,
         0.69708118,  0.05878503],
       [ 1.75598648,  0.6984303 , -0.37225618, ..., -0.7230443 ,
        -0.63172982, -0.63938976],
       [ 1.76410413,  0.6984303 , -0.37225618, ..., -0.7230443 ,
        -0.63172982, -0.63938976]])

In [34]:
previsoresdf = pd.DataFrame(previsores_esc)
previsoresdf

,0,1,2,3,4,5,6,7
0,-1.840135,0.698430,-0.372256,-1.039012,0.149065,0.833628,-0.631730,-0.097180
1,-1.832017,0.698430,-0.372256,-1.039012,-0.043230,0.833628,-0.631730,-0.335997
2,-1.819841,-1.431782,-0.372256,0.962453,1.174636,-0.723044,-0.631730,-0.352250
3,-1.803606,0.698430,3.520480,-1.039012,-2.030273,0.833628,0.697081,-0.814070
4,-1.799547,0.698430,-0.372256,-1.039012,1.431029,-0.723044,-0.631730,-0.684702
...,...,...,...,...,...,...,...,...
178,1.691045,0.698430,-0.372256,-1.039012,0.725949,0.833628,0.697081,-0.343166
179,1.695104,-1.431782,-0.372256,0.962453,-0.171426,-0.723044,-0.631730,-0.967737
180,1.723516,0.698430,-0.372256,-1.039012,1.302832,-0.723044,0.697081,0.058785
181,1.755986,0.698430,-0.372256,-1.039012,-1.068801,-0.723044,-0.631730,-0.639390
182,1.764104,0.698430,-0.372256,0.962453,-0.620113,-0.723044,-0.631730,-0.639390

## Treino e Teste

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
x_treino, x_teste, y_treino, y_teste = train_test_split(previsores_esc, alvo, test_size = 0.3, random_state = 0)

In [37]:
x_treino.shape

(128, 8)

In [38]:
x_teste.shape

(55, 8)

In [39]:
y_treino.shape

(128,)

In [40]:
y_teste.shape

(55,)

# Regressão Logística

In [41]:
from sklearn.linear_model import LogisticRegression

In [42]:
logistica = LogisticRegression(random_state=1, max_iter=500, penalty="l2",
                               tol=0.0001, C=2,solver="lbfgs")
logistica.fit(x_treino, y_treino)

LogisticRegression(C=2, max_iter=500, random_state=1)

In [43]:
logistica.intercept_

array([ 1.18291851, -3.24239763,  2.05947911])

In [44]:
logistica.coef_

array([[-0.01462397,  0.23226962, -0.30688702,  0.04476868,  0.09257434,
        -0.68957366,  0.31755256,  0.33323583],
       [-0.21348956, -0.32159491, -0.137769  , -0.20996604, -0.07733851,
         1.00470072, -0.96108064,  0.03340875],
       [ 0.22811353,  0.08932529,  0.44465602,  0.16519736, -0.01523584,
        -0.31512705,  0.64352808, -0.36664458]])

In [45]:
previsoes_logistica = logistica.predict(x_teste)
previsoes_logistica

array([2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2,
       0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2,
       2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2])

In [46]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [47]:
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_logistica) * 100.0))

Acurácia: 54.55%

In [48]:
confusion_matrix(y_teste, previsoes_logistica)

array([[ 4, 20],
       [ 5, 26]])

In [49]:
print(classification_report(y_teste, previsoes_logistica))

              precision    recall  f1-score   support

           0       0.44      0.17      0.24        24
           2       0.57      0.84      0.68        31

    accuracy                           0.55        55
   macro avg       0.50      0.50      0.46        55
weighted avg       0.51      0.55      0.49        55

**Análise dados de treino**

In [50]:
previsoes_treino = logistica.predict(x_treino)
previsoes_treino

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2])

In [51]:
accuracy_score(y_treino, previsoes_treino)

0.703125

In [52]:
confusion_matrix(y_treino, previsoes_treino)

array([[10,  0, 31],
       [ 0,  0,  2],
       [ 5,  0, 80]])

Regressão Logística = 54.55%%